apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress-route-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.local.floriangubler.ch`)
      priority: 10
      services:
        - name: prometheus-operated
          port: 9090
  tls:
    secretName: prometheus-certificate
    domains:
      - main: prometheus.local.floriangubler.ch
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: prometheus
spec:
  isCA: false
  dnsNames:
    - "prometheus.local.floriangubler.ch"
    - "*.prometheus.local.floriangubler.ch"
  secretName: prometheus-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io