apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.local.floriangubler.ch`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
  tls:
    secretName: argocd-certificate
    domains:
      - main: argocd.local.floriangubler.ch
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  isCA: false
  dnsNames:
    - "argocd.local.floriangubler.ch"
  secretName: argocd-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io