apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.local.floriangubler.ch`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 443