apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FlorianGubler/lithium
    targetRevision: HEAD
    path: cicd/cloudflare/cloudflare.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare