apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: gubler.florian@gmx.net
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: gubler.florian@gmx.net
            apiTokenSecretRef:
              name: cloudflare-dns-token
              key: apikey
        selector:
          dnsZones:
            - 'floriangubler.ch'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}