---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    apikey: AgAYyuFqfkul7jKgvW2sftk8h8MW4O1CqfNG6MJCUn4qylj2A6vGm5A1kFr6r3QnJVJ0WLLsUhFZzWVpyOvPsOvHqWz3G4SpLdy9fXQWL3oLOXigtNT3uM2Bu4QwSDW9TETEAUT6gDa3hTOqOlaVJcKd9nKusOe+wEwN/7Gil8iOEfZlypDj3QUzniEPcaFALo0XFjD2CNqA/nQPeSDwhsz2VczLvTWGrWVdrf2x4dClLOdCpUbFoS99NEL+U6MOQNhIQYgu68UwoKjay/3Eo5+BJqhlARrqaciDG0sA1P2xnEUUoi1x6BoEEEtJ2iTYuuGhtsPnzN1PQDngzT10zPYaWbCcICrBvnTvTVuIIZQSzNtw1dsY05n0ryv+ANOrBrKrQTkrMMxeGQBKYK/Yf8L9om1intCEmdBT2VECo9HSSL29Px3CKskjZfiaLkWdKPVt/kR9KZAkr7L43WYalcCYmqRxhHHB0sc/96AdL6H8t1e+FXmJZc7dH8vWIIuv7ty8qGcBM4XxFpB415NHUAvwU+DA8Ss0V+cRAXMUCjuW07vOB+v7bF33VAIZTjsz5D2u1fT/+tqYGFfp9HwxmmvNyFQgPuHXZjDpLnQYSytQIGg8cssoVzCEGDM9Z6HHp1FltrugWVgpuaeZhF637Ct9H/TYpU8zURxzOWrnGltvsg+LqdUTlgeAHMZjZymTu+wKZLKy3pnm8loaBwWzs2Sa96GJ0npu+TsvNIqb5ws/KIvEwfXtUJAk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
