---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: docker-auth
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBqRCoBNOwut+qBncO0hmysn6UNQZSTd7iPqBcFsK1XrAvkW5VBohSn4k5F+bqRSFJoD4fGToPVeYvlE17tHzE8MLaT4lgxm/k9+MguhgtoMctoCLjhsUhQzcDVKvsR6WtS8w1qdDLHdFx43G+0z2UuTkG6tigv04kzl/7bC/4LtoNfD5gGF/GBiJ7TEfiXzqFuOIBWWIUriBqaoRqIDUGdFp29VV2XzV5MR8z8oWkiqWGMmYtCtBwL/leuL8J6o34Pzg2+L0d+t3fmeqBJAlbSw4ioZA2ABv64UaaHGekvciL1xqG8DyTI9LCY17m5tesJg7n0K6Idcrl0VC0ig03oFsBzz/qFRNOvxxzqkoYKZD4vYQY0fXSaRm/FClDf5MK+xwnzgmpAup3S39hNvvilI5jHgFOUIZYUBdYzOgoRHIr693RhMcL0yTE5HjV1PjVYMr9bIeN3fteWJAD2jq/EiMXT3RYKBTHDPMX5uVQPK+uK7HHdkpvzO5XS1biXfnV6Wb4iU2nU8VH4W+1qFocV5qaVGnXE7qHAQFzuphElsW+1fojs57THGsQd3RsMBHXwYnD4IJTdca84EG5D+G0X4z+6Qv9AZQfZx0CwUsPE9VhJjEjeVbW3ASKP/vwOqQ4AeHH8adL2fvdq0nC2t94mBFPtxTOWSfgcGz7LIeru+qeQhg43zZ42CUJr3DxYVm4xHFqG8+6ossESDB3YJLhfQ6PyeMWGHcXUw3uYr7LGU9+zqTJvurC2voyUVpfPzFEeU3DwqCwX20Sv8ThXvw84Vomn+OQVu9dE1e4WfipAyV3oa49+b4Pqd1i3fvw/nyq92mn2UbqHu5oL62sL72sQ9LpFsNj1FM+AwIQu1/zu1EVZ+OIc6QCUZ0ZpKOU/AzOj7Hmv53Pqeu36bHyihpj8NOYkNxAS6ETM5QEJB2IoGV9nsfK7he0FkDUPp+wZxOvaAocF+98A0hD9FUS34Hj//n3hv7wP+Imr2NM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: docker-auth
      namespace: production
    type: kubernetes.io/dockerconfigjson
