apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-usb1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usb1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.mountNode }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-usb2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usb2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rasp-kube-node-001
