apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-access-binding-default
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ci-access
    namespace: default
roleRef:
  kind: ClusterRole
  name: ci-access-role
  apiGroup: rbac.authorization.k8s.io
