apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-access-role
  namespace: default
rules:
- apiGroups: [""]  # Core API group (pods, services, secrets, configmaps, etc.)
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]  # For deployments, replicasets, statefulsets, etc.
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]  # For jobs and cronjobs
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["cert-manager.io"]  # For jobs and cronjobs
  resources: ["*"]
  verbs: ["*"]
