apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-usb1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usb1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-usb2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usb2"