name: Deploy to Kubernetes
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
      chart:
        description: 'Deploy Component'
        required: true
        default: "*"
        type: choice
        options:
          - "*"
          - calico
          - cert-manager
          - ci-access
          - cloudflare
          - grafana
          - metallb
          - persistent-volumes
          - production
          - prometheus
          - sealed-secrets
          - traefik
jobs:
  call-deploy:
    runs-on: 
      group: lithium-{{ github.event.inputs.environment }}
      
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4
    
    - name: Extract branch
      shell: bash
      run: echo "revision=$( echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//-/g')" >> $GITHUB_OUTPUT
      id: branch
        
    - name: Deploy the Helm chart(s)
      run: | 
        CHART_NAME=${{ github.event.inputs.chart }}
        ENVIRONMENT=${{ github.event.inputs.environment }}
        if [[ "$CHART_NAME" == "*" ]]; then
          CHART_PATHS=$(find ./charts -mindepth 1 -maxdepth 1 -type d)
        else
          CHART_PATHS="./charts/$CHART_NAME"
        fi

        for path in $CHART_PATHS; do
          echo "Deploying $path to $ENVIRONMENT"
          helm upgrade --install $(basename "$path") "$path" \
            --values "$path/$ENVIRONMENT/values.yaml"
        done
      
