name: Deploy to Kubernetes
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
      chart:
        description: 'Deploy Component'
        required: true
        default: "*"
        type: choice
        options:
          - "*"
          - calico
          - cert-manager
          - ci-access
          - cloudflare
          - grafana
          - metallb
          - persistent-volumes
          - production
          - prometheus
          - sealed-secrets
          - traefik
jobs:
  call-deploy:
    runs-on: 
      group: lithium-development
    steps:
      - uses: actions/checkout@v4
      
