---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBzTVQajAnfe4sP+E8r85FSouejBJBKnSgWcmdGJUh70kWyzamjDZpI6tZzGCajx9/lggmCC8CpzLQB2VMpk2iCWyadaa4zAUufjmFbcCeKRCBNAu7dxP3vUecGMxAl2eKxvJJduLYmTUfpoNuZOGlulHPbPKAC/n4B1UAlb3iWjDrYsG4Ae1Y0XxiJhvdCsM1I4lsqS1s6SatKbLix6Ry9GC32wuKLZooq551oz1jirR6x04Z4dFLoZbyzTne9NtRNtwMkL6DA/j5IV+8L/BUDm5aJMOx7+k9C6evJq/vfepBHWxmE1ySICxQ5omQtAMVIxLn+yusAUUu29MDnSnSpSt9TmvBB2imHg2IXOEZOCWHJX2t3BWc+oNrDVUyencrebUGZ+E8QOQtKo3tz8cGgnlQw9BkUIAdDg300l0tos43M6dbDHdC7OD/Ju8rfb2DRuPZbsRI+Kf2lIs+F805jidsJqQtVu5wX76rxE4s/oh1OC3G6RwH3Ca5Kpe988DNX7mqoPEoUCQVbvvKovQ8YEM0XTViBuaRlamC7BI0MJ3GuoBEgvpnMOPuHIHg8+ndu4/yVjQ/qSEPZZdwNlAj7wiGqo5/G6HFgpQkslD98C/d5R7igIcuPzj6i91wriHA5k9Y1WM+MWAzl10lmgR5pknSUIXYMQWnMztbLWhDptJpNmVHwLNfcy9oUyQvYFaLYi0MtIrXNd2myATkRvhEdbIbPFyP8bBo+17pnDZFYZHABgS8RMyjy9wvBOilvQmv2qhmfcWo9OLale5FWhOsHrkTM+az4Q2hRz3QUnF1029Z1vhJ/xddspIUbolcSAatO6i3yrpPnvfRKmG8ATjwCwyLniGY6l8PVtET7fJ7FJNIkloAZ1T5ZQEHUGVO3LiEY75KOdI9mwzXFLv8WoCwl2X1jeGU/hkxtPEzjdOkxmK4DW91uqzyO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: cloudflare
