---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: docker-auth
  namespace: cloudflare
spec:
  encryptedData:
    .dockerconfigjson: AgCKdh28LGnwqfFpPyY/SvH4cjRUhq+kOLCoqzJSMagBdJd+ra4jcQlAxccMxF8CYnoUfIyIXJiGnaiziwsGGerh8TjLqoB+Yn2+uYVPR3pMPHW2Ucw8O8Un4nuYorUhvaZcSJs6SGyF15ZIHCRFdF9KS/14GVqU0VKEHFj0arlPHlrIL858p3UfjgK6psDDGwZyPKkPViKpf3VfLSCYQCvqGVp6LHZxcfoVdyL6kPkoT5Qs6xVBtOQa+nbp6+qfAhC+Q+HKvU/8+bsXZszkWaVKe/ojjWwxH0ctv34My8SaVMGfhC1FPvpORtve8Y/a/RUtmbNmMo559QczhrJ8Avn6NcMqv26cE/8FNj/I3iMweISrJuB4vPetgVfg8hoCqQr0nASCCHny99T6PXBkiZH/4V6FL4mkzEN9IZM/f1ZWcw1XvNgCZeSecs4UNj5JP9VxmJmMgDhT/itv5TNUKPARtkmlnqgyW2dnzeF+zZORwaCpsWn5EvqocaxdN6P00WCrxq7Ps6f/owIxAcmyqIxnIiVboZ6dkOqFqXXbA23RiEcsl3TLQHkRpq3Pk/UZZR5SnjtA6If0r/6i8SIS9esiJWHdqip+dEJFJBDVYKu3HXtlcTxgIVuO9s9tDzvHpWju4nXS6GsKmQrHEQGlDT/9LLS9ZgSstUCcq/SXtJSK00Fj7rOzzj9J143JE6jFtDwcP5IEdd+DrIpzx8yBG0eYWEltHK5qAFVHQY+ohtyCY5VTA+Qk+ctpU5EOlFAmPKm9rkA/t+1M2ShA/+do8PBn46gvZ2x4ZIvzNB7OjYxupXQ2xv+m59lOKbiCOwLbhet7ForqzMPb8tqLiGUBCgSaUwJIFOHpUNuCGMZGvHSTZfqbM+yJTB/JUtwuL9azfMLuul44qYTUwodUPND34n1c4HIS0sGWrNLkhEVKCKhQwmmma1y1NSyie5dLW5wFsQyEloWbH+ko6MpwWK5a+oelMSzSxlLi9HJ6DwfP69z7CXE97S2aW//bWYrOZSLLQQ8rjNFxx9dm2KwhCJfWpHvwB0jEEC1BwWVncrTwbwEDcbUzyYuaF2xxUok4BLbxnJ4WJA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: docker-auth
      namespace: cloudflare
    type: kubernetes.io/dockerconfigjson
